name: flutter_gps
description: Sistema de control de asistencia para obras de construcción

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Firebase dependencies
  firebase_core: ^2.32.0
  firebase_auth: ^4.17.8
  cloud_firestore: ^4.15.5
  
  # Location services
  geolocator: ^10.1.0
  permission_handler: ^11.0.1
  
  # State management & utilities
  provider: ^6.1.1
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/