name: flutter_gps
description: Sistema de control de asistencia para obras de construcción

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  firebase_auth: ^6.0.2
  flutter:
    sdk: flutter
  geolocator: ^14.0.2
  provider: ^6.1.5+1
  shared_preferences: ^2.2.2 


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true